# The Des Moines Lobe I

6/3/2019 

## River Warren Outcrops Scientific and Natural Area  [FFS 68 ]

* Normally don’t find bedrock in this region of the state.  However, the draining of Glacial Lake Warren cut down through the glacial sediment here, exposing bedrock outcrops in the MN River Valley 
* We are in a floodplain here - ecological classification FFS 68
* Native vegetation is silver maple, box elder, oak, cedar 
* Historically, you would have found wet and mesic prairies here in this region.  Now, there is almost no wet or mesic prairie left - all agricultural land 
* Wet prairie WPS 54
* Mesic prairie UPS 23
* We see gneiss bedrock exposed here (Morton gneiss) 

##Brad Meyers’ farm  

Zone sampling - class will take 3 samples in each of 6 zones (map units) in this field.  Nic will send them in for testing: P,K, OM, pH, S  

L201A  
I370B  
L83A  
423  
1370B  
1355B  

Nic references MN Geological Survey gridded maps of elemental variability in the subsoil. 
Class looks at the drainage ditch near Brad’s alfalfa fields. Observe how deep the ditchere here have to be to get water to drain.  In most fields tile lines are ~3 feet deep according to Brad 
Most of this Des Moines Till landscape is tile drained 
 
**Conversation with Brad**

* Brad and his family are cropping livestock farmers 
* They have 1000 ewes and grow all feed for them. Manure goes back on the field.  They work 1000 acres 
* This is “high alkali” land.  When Brad was born, this land was covered in cattail sloughs
* Now, the only cattail sloughs remaining are on his home farm - about 10 acres total.  Brad likes to see wildlife there, he is proud of it and protecting it 
* Comments that he is probably the last moldboard plower in the township
* For Brad, a big part of the decision to farm the way he does is economics.  1000 acres is not enough to support 2 families (Brad and his son farm together).  Also can’t afford to spend lots of $ on new equipment for conservation tillage 
* It takes skill to do moldboard plow right
* Some of the benefits of moldboard plowing are: helps soil warm up and deals with weed issues 
* He has tried no till south of his driveway for 2 years - resulted in big thistle patches 
* Have incorporated some cover crops - mainly because of the advantage they provide for grazing sheep. 
* Has neighbors doing cover crops without livestock, and those neighbors have limited success.  Brad thinks that we are too far north in MN for cover crops to work very well.  Sees poor stands at neighbors, and some have invested in expense equipment 
* Brad has had issues with cover crops plugging tile lines. This is frustrating and expensive to fix.  Root hairs hit the tile line, find oxygen and explode in growth.  Find big “brillo pads” of roots in the lines 
* Mix that plugged the lines:  3 lb radish / 3 lb turnip / 1 bu oats 
* Mix that hasn’t plugged the lines:  1 lb radish / 2 lb dwarf Essex rape 
* Typically seeds CCs last week of July, tries to time the maturity of species with peak nutritional value for sheep.  Mainly use these CCs to flush * Ewes with nutrients at ovulation.  His lamb crop has exploded since he started doing this 7 years ago - increased 170-200% ! 
* Lets ewes graze out the cover crop until January when they can’t find it under the snow.  Brings up the “nutrition plane” ? and length of grazing with cover crops
* When he was breeding Aug - October, pastures are typically declining in nutritional value.  CCs help fix this 

**The Farm Business** 

* Sheep are a big part of their income.  Cropping is more of a sideline.  It’s difficult to earn a living farming.  Keeps the amount of land he has to have consistent feed for his sheep and place to put the manure. 
* Using manure on the fields saves them $75/acre, but they have to rent manure trucks to take the manure to their fields further out
* In 1992 hired crop consultant to test ground at the home farm.  Won’t have to add fertility to his home fields for the rest of his career!  * * * * History of putting manure on the fields (for 20 years), nutrient levels are very high 
* Brad and his son lamb 1000 ewes each year, and buy 3000-5000 lambs per year to finish for market 
* Sells lamb directly to slaughterhouse in CO.  When Brad was 25, he had 5 choices for slaughterhouses within 500 miles.  Now he has to go to CO with his lambs 
* Has considered direct marketing lamb, but it would be difficult to do at scale.  Typically people who are direct marketing have a small number of animals and primary income coming from off-farm. 
* Cost of seed 
    + Brad has been a loyal customer of Pioneer Corn for many years, but they were purchased by another company - comments that it’s almost like we don’t have anti-trust laws anymore! 
    + Now seed is $396 a bag.  1 bag covers 2.6 acres 
* Farm margins keep getting thinner and thinner.  When son Dusty came home and wanted to farm, Brad saw two options: 
    +  More sheep 
    + Fight with neighbors for more land
 

>“Sheep are not easily automated. That creates opportunity. Automation takes little independent guys out of it.”  
>
>~Brad Meyers

**Why did Brad pick sheep specifically?** 

* Did a sheep 4H project when he was 10 years old.  Fell in love with them.  Learned everything he knows from other people and the school of hard knocks 
* Lambs aren’t traded on Chicago Mercantile.  Keeps investors from trading his product and trading profits out before the lambs even reach market weight 

>“The day they start trading lambs on the board, I quit. Our market is true supply and demand.  That’s what has happened to the cattle and hog industry, those folks have become slaves, slave labor.”  
>
>~Brad Meyers

* Brad has had 3 bankers scorn him for sticking with sheep. 

>“I view a laugh as a stroke of opportunity. When people laugh and don’t do what you do, that’s an opportunity.” 
>
>~Brad Meyers


How does sheep manure compare to other manure on the market? 

**Coyotes**

* Coyotes have been one of his biggest challenges. Story about paying someone else to trap coyotes for $50 each, and Brad ended up writing a check for 3,000. 
* Coyote population has been growing - losing 10s of ewes in 2 months on some pastures. First he tried donkeys, then livestock guardian dogs (Great Pyrenees). Dogs were close to 100% effective, but some of his neighbors got angry when dogs would escape and end up on their property - threaten to shoot the dogs.  
* Brad loses $250 each time he loses a ewe.  He does carry insurance on the animals, but it’s hard to afford >$1,000 deductible each time

6 ton yield calculation - Brad wants this worked into soil testing so he knows whether to fertilize after first ??? 

**Buffer Law**

* Buffer law - 125,000 acres of cropland lost in 2 neighboring counties to the buffer 
* Still have to pay taxes on that land! 
* Brad points out how ditch banks are shaped - is there really runoff when the bank is sloped away from the ditch? 
* Brad agrees that some spots might need a buffer, but not everywhere as a blanket 
* Brad is very careful with his practices to protect water quality - stays 300 feet from tile intake with his manure spreader, spreads in the fall and tills it in. 
* Gully on the neighbor’s property - Was fixed and now it’s becoming a problem again (we’ll see this later today) 
* Reinstalled tile deeper, filled in gully with more clay, put in fabric every so often to curb erosion 

**Catena @ Brad’s Farm** 

* Texture are loams and silty clay loams  
* 10YR / 2.5 Y  
* See shale fragments in Des Moines Lobe Till ground moraine  
* Carbonates to surface at the summit position - under natural conditions, we would expect to see carbonates deeper at the summit because water infiltrates here  
* Tillage erosion most effective on summit and shoulder - after 150 years of erosion we see parent material at the surface.  

Summit: hapludoll  

Backslope: inceptisol / Vess   

Vess series is mapped in this area on eroded knolls (and throughout the state). Classified as an inceptisol, but is actually an eroded mollisol  

Depression:  

* Webster series. 
* No carbonate in profile.  
* Historically this would have been a wet meadow. In dry times of year, water moves from the depression out to the edges via capillary action.
* We see carbonates here in a ring ~30 feet from the depression 

##Grant & Dawn Breitkreutz

* When started farming 22 years ago, they were doing full-width tillage and it wasn’t working financially 
* They have a cow-calf operation, custom finish other cattle.
* Years ago, they started to run out of feed for their mama cows - this is when they started studying grass management 
* Important influences on Grant/Dawn’s thinking: 
    + Ian Mitchell (?) from South Africa (mob grazing?) 
    + Gabe Brown 
    + Ray Archuleta
    + Allen Williams 
    + Burleigh County, ND - innovations in cover crops.  Relay cropping, no-till.  Manokin Farm? 
    + David Brandt (OH): developed 24-48 inches of black dirt on his farm, had a soil named after him. From Ohio.  Developed 24-48 inches of black dirt on his farms

**Management Changes**

* Within 7 years of starting new practices, they had quadrupled grass production and reduced herbicides and pesticides on grazing land (check this not sure what the 7 years applies to or if it’s correct) 
* In 1998 Grant and Dawn bought their first no-till drill 
* They knew the practices were really working when they got 1.75 inches of rain and still had the hay cut within 6 hours of the rain 
* 2007 they started doing no-till small grains 
* Were hesitant to switch to no till corn because they though they needed expensive equipment 
* When tilling, they used to pick lots of rocks 
* Now they are 100% no-till.  Put in cover crop while crop is growing or immediately after harvest.  * High priority to keep a living root in the soil all the time
* Plant corn, after 2-3 weeks they interseed cover crops into the planted corn.  
* Cereal rye is their go-to cover crop, vetch is another important one for them.  
* In their rotation they do Corn - Soy - Small grains, hay included in rotation sometimes too 
* Their cover crop species mix changes depending on the conditions, season, state of the land.  
* They notice that their soil biology breaks down cover crops so quickly; residue doesn’t stick around very long 
* Mention that the animals are a key part of the operation and contribute to soil health, but it’s currently hard to quantify that. Rick Haney & Lance Gunderson (Ward Labs) are working on that. 
* Grant comments that mycorrhizal fungi are very important for soil health
* Grant and Dawn run cows across every acre at least once per year.  Cows add important biology to the soil!  
* They need flexibility in their operation to respond to the seasonal conditions and changes.  Keep records of where they graze and what they plan on all their acres.  
* Typically with managed grazing the cows are getting moved every 1-3 days. 
* Grant and Dawn use earthworms as a soil health indicator.  They have calculated that they have 1 million per acre on their cropland and 850,000 per acre on their managed pasture. They no longer worm their cattle because they don’t want to kill the worms out in the pasture!  
* In pastures they are constantly seeing an increase in species and composition of pasture plants. Also many different birds & wildlife 
* Grant mentions “Farmers Footprint” documentary series - Grant and Dawn featured in this.  https://farmersfootprint.us/  
* Have reduced inputs to almost nothing but still get 160-240 bushels corn in yield
* Having 3-4 crops in the rotation has broken the insect cycle so they aren’t experiences the same levels of insect pests.  Have not sprayed insecticide in 6 years, no fungicide sprayed in 8 years
* Herbicide use cut in half, applying only 10% of the fertility they used to 
* They have a great predatory insect population now that they have stopped spraying.  
* Grant comments that it would be a slower process to transition to this type of system (100% no till, cover crops, drastically reduced inputs) without cows.  The cows are an essential part of the system for them 
* Grant and Dawn have not experienced a yield drag on their cash grain crops ; they believe others who only do 2 crops in their rotation, and don’t include animals would experience a yield drag
* Grant thinks you can see a big impact on the soil health in 1 year with cows, but it would take 3-5 years without cows 
* Grant and Dawn are currently trying to rehabilitate some DNR land across the river - they can’t put cows on it (because of DNR rules) so they have been using cover crops on it.  This is their 5th year growing cover crops on it 
* Last 3 years have been very wet.  Grant reports rain during growing season: 
    + Last year: 44 inches
    + 2 years ago: 41 inches
    + 3 years ago: 36 inches
* Have noticed an incredible increase in water infiltration rate - Grant claims they can infiltrate 30-50 inches per day now on some of their land.

**Markets & economics**

* A key part of making sustainable farming work is making sure there are markets opening up that reward farmers for doing these practices, diversifying their operations. At this point, the end processors (General Mills, Land O Lakes) are approaching farmers directly because there is a consumer demand for sustainability they want to fill.  
* Gabe Brown has developed some soil health criteria for General Mills -- but Grant and Dawn don’t feel restricted by this criteria.  
* Grant comments that 85-90% of the input purchases that farmers make are directly dictated by what their input suppliers tell them; important for folks to think for themselves about their needs
* Another economic challenge to diversifying farm systems is that there are (currently) a limited number of insurable crops:  corn, soy, sugar beets.  Loan officers resistant to supporting alternative types of farming systems 
* Big picture -- the agricultural system is currently focused on PRODUCTION.  Grant advocates that everyone should be focused on NET PROFIT.  
* Grant and Dawn have observed that soil erosion has magnified since they started farming ; they can look at their neighbors’ fields after a 1 inch rain (falling over 3 hours) and see standing water. * * However on G & D’s land, springs are starting to form again on their hills 
* G & D don’t have to worry so much about trafficability and compaction anymore - their soil has the structure 
* Comparing where we are on a little hill at G&D’s farm, the structure and color of the soil are very different.  Here we see darker color, more aggregation.  

##Back at Brad’s Ditch & Field

* Class observes tile drain running after a brief rainfaill 
* Buffers don’t protect N or P in a watershed that is tile-drained (like SW MN) 
 land use patterns are too complex for a silver bullet solution like buffers to be advocated everywhere  -- there are multiple ways to get sediment into rivers and streams, need to think about which mechanisms are relevant in a given place 
* For the MN River, bank erosion contributes a significant amount of sediment 
* In this region, tile drainage conveys nitrate out into waterways 
* UMN does lots of research in this area - Jeff Strock at Lamberton is investigating how long the tiles flow each year
* Class observes the surface intake (vertical pipe) in Brad’s field.  These are usually placed in depressions where you would historically have ponding.  Sediment can travel down through these intakes and be transported through the tile lines, sometimes carrying P with it.  
* The soil we are observing here in the depression in Brad’s field is a typical Webster.  No effervescence along the surface within the depression radius.  You do see effervescence in a ring around the depression

##Gully on neighbor’s land 

* Class observes a gully on a neighbor’s land.  Recent attempts were made to repair the gully; silt fence is visible.  However, continued erosion has already overwhelmed these efforts and the gully seems to be opening again.  
* Tile drainage is visible on the surface here where it has been exposed/ripped up. 
* For the last 2 years, this gully was almost as deep as Nic is tall! 
* Class looks at the “nick point” ; this is where headward erosion of the gully takes place 
* This land is leased to Brad’s neighbors who farm lots of acres; Brad thinks this should have been maintained as a grassed waterway the whole time. Perennial cover would help stabilize the soil here 
* Landowners now have contract with the NRCS to fix this gully 
* Gullies can generate huge amounts of sediments in a short period of time; some studies show that “hotspots” on the landscape like gullies contribute lots of sediment to local waterways 

##Brad’s Cattail Slough 

(MRP 83 - Prairie Mixed Cattail Marsh) 

* This is one of the biggest undrained wetlands in this and surrounding counties. It is a pothole wetland.  Brad is quite proud of it. 
* In native states, the small depression we saw drained in fields would have looked like this
* Reed canary grass present.  It is listed as both an invasive species AND an important grazing species 
* In terms of moisture level, pothole wetlands > wet prairie > mesic prairie 
* As you get to the mesic prairie areas you would see Canisteo soil present 

