# The Driftless II

June 7, 2019

**Morning Review** 

*  Brad, Grant & Dawn are unique as farms on the Des Moines Lobe till because they have animals in corn country 
*  The topography in the Driftless area drives diverse land use 

##Hyde Park Holsteins
 *  Introducing Kevin Sewert (sp?) and herdsman Eric 
 
**Milking parlor**

 *  This is a pretty advanced set-up; data on each cow is tracked and associated with a number recognized by the milking machine 
* 90 cows can be milked each hour
* 3 milking times per day.  2am, 10am, 6pm
*  Soon they will be expanding the barn to hold more cows.  They will transition to a 24 hour/day operation 
*  Produce 6500 gallons of milk per day 

**Talking to Kevin**

*  One challenge is figuring out how to use the manure that is generated.  Tillage is required to incorporate it into the fields 
*  They use all strip-till on the farm.  This is in contrast to many neighbors who also grow corn and soy 
*  Dairy was built in 1995
*  Each cow produced 110lb milk per day 
* They have started using sand bedding for the cows. This allows the cows to stay cleaner and measures of milk quality to increase (somatic cell count - lower is better) 
*  They group cows together based on how quickly they milk - the slow milkers go together 
*  Takes 4-5 minutes to milk one cow 
*  The cows have pedometers that can track how active they are- this is a good indicator of who is in estrus 
*  McDonalds is a big guyer of dairy cow meat
*  Improved genetics are an important part of their program for raising productive cows. They use genomics for selecting bulls, 4H animals 
*  Manure management - now that they have switched to sand on the ground for manure, needed to install a flume so they can flush manure out of barn, reclaim sand 

**Cow nutrition** 

*  What is silage?  It is the entire green part of the plant, chopped fine.  It is apprx 72% water, should not be able to see corn kernels in ideal silage 
*  On this farm, 300 acres silage and 500 acres hay 
*  Key to making good feed is right moisture, pack tight 
*  In addition to silage, they use a number of byproducts to blend feed for the cows
    +  Whey product 
    +  Cotton seeds 
    +  Ground up corn 
    +  Canola seed 
*  Cows diets should be balanced on amino acids 
*  Costs $9/cow / day to feed 
*  This is the highest producing herd in the state(in terms of milk per cow), maybe top 20 in nation.  Kevin attributes this to good people
* Discussion of BST (Bovine somatotrophin) - processors said they wouldn't take any milk with BST, cost the business money.  Kevin talks about the importance of consumers understanding the utility of technology in farming businesses.  Technology needs to be used to benefit society

**Farm Background & History** 

*  History of farm 
    +  1942 Grandpa bought farm 
    +  1970 Kevin left teaching - he was a professor of Ruminant Nutrition at the University of I (Illinois? Iowa?), came back home to farm 
    +  1995 - up until this point milked 60 cows
*  More about manure management - with a CAFO permit you can't have any runoff from the facility, have to collect every drop of manure 
    +  Can apply to land within 5 miles (fact check this) 
    +  Must collect water from any cement an animal has touched.  In a 1 inch rain they collect 1 million gallons of water
    +  They inject the manure into the fields with a tractor implmement 
    +  They collect so much water that the N in the manure is diluted.  Real value of the manure is the P and K it can provide the crop 
    +  They apply manure in Oct/Nov.  Cool temps important to make sure you aren't losing N (through denitrification)
    +  Come back in the spring and sidedress with a little N to provide what the crops need 
*  All soil grid tested every 3 years to check on where it is OK to apply the cyclone lime they use as bedding for the heifers. Don't want soil pH to rise too high
*  In general, rising costs to run the business. They need to stay in a growth phase to be viable 
*  Kevin's son Justin wants to come back home and farm 
*  Where is the milk sold?  AMPI (cheese) in Rochester.  Also sell to a company in Blair WI that makes powdered dry milk.  
*  Milk is processed by different facilities into fluid, powder, cheese 
*  Kevin talks about divisions among farmers based on practices - organic vs conventional 
*  Kevin's biggest concern is erosion.  Drain tile works very well for him, says it makes a huge difference in the wet heavy spots. 
*  Next spring they will be trenching again for tile - Nic wants to drive down! 

##Quarry 
*  This used to be agricultural land 
*  See loess over limestone/sandstone residuum here 
*  Good clay films - illuviation down through loess into reddish residuum 
*  Residuum - sandy gravelly clay loam 
*  What is saprolite - things that retain original rock structure but are chemically modified
*  Limestone residuum is typically redder.  When limestone weathers, everything dissolves except impurities like iron and titanium
*  Limesonte residuum is clayier and redder.  Typically has cherty coarse fragments 

##Catena in Kevin's cornfield 
* Summit:  Mt Carrol Series - deep loess.  Mollic hapludalf (savannah type).  Argillic horizon likely

* Backslope (convex):  convex in profile and plan view.  No clay pick-up.  Less infiltration to illuviate clay on backslope compared to summit.  This is a typic hapludalf.  This is a water-shedding landform

* Backslope (concave): Even wetter than depression soil? This is a mollisol, unlike the convex backslope. We are looking at an oxiaquic hapludoll 

* Footslope: Very dark colors, cumulic hapluodll.  

* The upland positions in this catena are eroded from tillage and water erosion 

* You find the best argillics on the summit positions of these landscapes 

* Typically find the thickest loess on the East side of the Mississippi River because winds typically trend W to E.  

##Dry Creek Farms
6/7/19 John & Jared Luhman 

*  Manage 700 acres land, 250 organic cropping and 450 pasture/hay for forage and feed 
* Approx 200 cows, raise bulls 
*  Cover crops - hay or graze.  Plant sorghum sudan grass.  Usually they leave the sorghum sudan in the ground until fall, graze it in the winter.  This helps them reduce their feeding costs in the winter, which is the most expensive time 
*  Using annual cover crops has been a great way to reduce winter feed costs.  They are typically grazing until the first week of January! This saves 2-3 months of costs, labor, time.  
*  Since they started grazing the sorghum sudan, they have seen great soil improvements. Less weed pressure. 
*  They are working with some no-till farmers this year, experimenting with bringing their cows over to other peoples farms to graze down cornstalks and help improve a poor field with bad soil.  
*  Cost comparison
    +  In winter $3 per cow per day to feed
    +  $1.60 per cow per day grazing cover crops 
    +  $0.50 per cow per day grazing corn stalks 
*  In the livestock industry, animals have been separated from the land.  Crops and animal production systems have been separated. As people move toward more integrative systems, there are great opportunities for crop farmers and livestock farmers to work togehter 
*  Perennial weeds are their biggest problem when moving to no-till in an organic system.  Probably need to till every couple years to control weeds. 
*  In 1962 they bought the farm.  Converted to organic in 2000
*  They see the harm in tillage now more than they did before.  
*  Like Grant and Dawn, John and Jared emphasize thinking about profit per acre, not maximum production as the overall goal.  
*  Hypothetical question; if you are pursuing maximum production, what happens when you are totally dependent on outside intpus and debt just to run your business? 
*  John and Jared are working hard to develop a self-sustaining system - part of this is the type of cattle they raise.  They have smaller framed animals.  This allows them to produce more pounds of animal and more profit per acre compared to bigger animals. (Can fit more small animals per acre).  Bigger calf means bigger cow means more feed!  Smaller animals can be more efficient in their system.

**Adapting animals to fit the system** 

*  They only keep animals that fit their system - let the environment decide
*  They breed for a more moderate size of cattle.  Big cattle need a system based on corn - moderate sized animals can survive just on forage.  They breed primarily Red Angus cows
*  Takes John and Jared 18-21 to finish a grass-fed cow.  The conventional beef industry takes 15 months
*  Most of the beef industry is calving January and February.  When calving, cows need the best, most high quality forage (Jan and Feb not a good time for this!).  John and Jared calve in May when they can take advantage of high quality grass in the spring and early summer. 
*  For animals, think about maintenance energy. The conventional dairy industry is looking for maximum milk production.  No energy left for the animal to put on fat or get rebred 
*  From John & Jared's perspective, farming is about turning solar energy into carbon and BEEF.  Leaves are their solar panels! "Sunlight is the only free resource farmers get"  (quote from Jared) 
*  Perennials and grasses can capture more C for more of the year than corn 
*  Building organic matter and C in soil benefits the whole system - trying to capitalize on that 
*  Emphasizes thinking about the sustainability of the whole system.  It's more than just the animal
*  There are many benefits to a more diverse diet for animals.  Their animals have fewer health issues now that they are eating a more diverse diet.  
*  Diveristy in pasture species is important too - this year they will have 11 different species in the annual pasture 
*  The majority of their animals go to wholesale. Jared and his wife are growing a direct-market beef businesses.  "The Grassfed Meat Market" 
*  They see perennial pasture as a middle ground between organic (including tillage) and a conventional spray system 
*  Currently they buy and apply some manure, but hoping that after this year cover crops will supply N for their corn crop
*  Books recommended by John and Jared - Gabe Brown's "Dirt to Soil" and "How Cows Save the Planet""
*  In spring, there is a risk of the cows walking on wet soil and compacting it
*  Giant ragweed is biggest problem weed for them 
*  Jared has started business called Grassfed Cattle Company with his wife 

###Soil at Dry Creek Farms

*  Most soils on the farm have about 3% organic matter.  Some long term pasture areas are at 6%
*  At the summit: silt loam, some clay pick up.  If argillic horizon is absent here, probably due to erosion.  Savannah type A horizon. 
*  Depression: Original soil surface is all the way down at 40cm.  Can see where the color gets darker.  Textures all silt loams - recall that silt loams are the most erodible soil type 
*  Des Moines Lobe - buffers as management strategy
*  Driftless - see many more conservation ag practices. Topography and soil type can make management challenging
*  Period of maximum erosion in Driftless area -has already passed based on isotope data [Nic references papers about this]
*  Studies of 1960s-1980s peak sediment in Lake Pepin 
*  People in the area don’t use moldboard plow much anymore, HOWEVER, one current issue is when people take separate fields (with different soil types & topography) and combine them into one big section rather than using contour strips which take a longer time to plant.  
*  John thinks people around here don’t want to take the extra time to plant and deal with contour strips 
*  John reports a “gully washing rain” a few days ego - erosion was evident in neighboring fields 
*  Soil conservation is an ongoing battle that everyone is involved in.  Consumers drive land use patterns with consumption. 
*  It can be a struggle make enough money to survive and not contribute to erosion?  * Soil is our #1 export - lose more than we harvest in a given year in grain 
* Class looks at a mini-sinkhole on the land : in limestone, could have a cavity that gives way and soil falls into the hole.  
