# Miscellaneous Logistical Notes

This is a chapter dedicated to logistical notes, and ideas/improvements for future iterations of SOIL 4511





MISCELLANEOUS NOTES

* Need additional 30-45 minutes at Brad’s farm
* Bring a separate soap container so the pump doesn’t make a mess in the paper towel container
* Separate smaller tote for coffee materials for easy access
* Need a new good ladle  (accidentally left it at SWROC) 
* Buy a folding table 
* Buy a tripod for phone to take group pics (like the one Mike has) 
* Other ideas for the guidebook:  LIDAR hill shade, aerial photos, letters from military expedition through Red River Valley 
* At Featherstone it took 1.5 hours to do the SW / Upland / NE cores to examine impact of aspect on soil. 
* Jack Hadine offered that if we would like to see other fields around his neighborhood he could help - knows most people in the area
* Kevin Sewert plans to trench for drain tile in spring 2020 - Nic mentioned wanting to drive down and see this process 
* Remember to send diagram and descriptions of soils from the UMN CBS properties to Jonathan


**nice cross-section figures of how landscape evolved through glacial cycles - glacial advance, retreat, loess deposition. 
Anders, A.M. et al., 2018. Impacts of Quaternary History on Critical Zone Structure and Processes: Examples and a Conceptual Model From the Intensively Managed Landscapes Critical Zone Observatory. Frontiers in Earth Science, 6, pp.Frontiers in Earth Science, March 20, 2018

